##
##  Makefile -- Build procedure for sample download_token Apache module
##  Autogenerated via ``apxs -n download_token -g''.
##

builddir=.
top_srcdir=/usr/lib/apache2
top_builddir=/usr/lib/apache2
include /usr/lib/apache2/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_download_token.o mod_download_token.lo mod_download_token.slo mod_download_token.la 

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop
